### ISSUE TITLE
it's not  working  function 

### ISSUE THREAD

**Issue by infernalslam** [TonPC64/gosuki#1]
```go
func checkPrime(num int) bool {
	flag := true
	for i := 2; i <= num/2; i++ {
		if num%i == 0 {
			flag = false
			break
		}
	}
	return flag
}
```

// test function 
numbers := []int {1, 2, 3}
why ? result : 6 is not 5 because first loop => 1 / 2 = 0.5 number is round up is 1
I'm happy for green point in github
goodluck and have fun!

**Comment by TonPC64** [comment]
Forget case number less than 1 return false in function
